Change most reference to slack to point to the forum
openbikesensor/openbikesensor.github.io pull request #110
Opened 2021-11-12 10:39 UTC by opatut

Also updates the community pages, the slack entrypage, the landing page, adds `/contact` and `/kontakt` aliases to the community page, and changes lots of wording for referencing to the community and ways to contact it.

2021-11-12 18:31 UTC, gluap commented on content/docs/user-guide/simra/index.de.md
>  Wir haben uns dazu entschieden, Bluetooth *vorläufig* auszubauen, da es das am
DIeser Block ist im anderen Review schon entfernt.

2021-11-12 18:37 UTC, gluap commented on content/_index.de.html
> +Wer noch Ideen zur Visualisierung, Automatisierung, Programmierung, Auswertung, etc. hat oder einfach am Projekt interessiert ist und mitgestalten will, ist herzlich <a href="{{< relref "/community"
... in **die** community eingeladen ...

2021-11-12 19:07 UTC, gluap requested changes
I apologize for my edit requiring two changes and the messy review style mixing review and comments, This is my next-to-first github review as reviewer. 

One thing is left: There's an additional mention of the slack group order channel in 
``content/faq/build/where-do-i-get-a-sensor.de.md``

I proof-read the text and built the change with hugo successfully.

2021-11-14 12:51 UTC, opatut commented on content/docs/user-guide/simra/index.de.md
>  Wir haben uns dazu entschieden, Bluetooth *vorläufig* auszubauen, da es das am
Ja, darum lasse ich ihn hier drin. Git wird das schon mergen.

2021-11-14 12:55 UTC, opatut commented on content/_index.en.html
> +Whatever we create, we make open source. Everything is available on GitHub,
> We publish everything we create as open source.

I went for this, a bit shorter. Good suggestion though ;)

2021-11-14 13:07 UTC, opatut commented
Thanks @gluap, I applied your suggestions, or at least most of them ;) Please recheck?

2021-11-14 13:20 UTC, gluap approved these changes

2021-11-14 16:11 UTC, merged