Add LGPL-3.0 license
openbikesensor/openbikesensor.github.io pull request #59
Opened 2021-03-24 11:58 UTC by opatut

Sadly, we cannot edit all our content files and add license headers everywhere (html. markdown, ...). But at least we can put the license into the repository and say that we use it.

I've added a custom section to the readme explaining that not necessarily all files are subject to LGPL, but only content generated by and for the website are. This is a bit messy, but I'm not sure how to better do it. Suggestions?

Of course, we have to take care, if we take for example media files (images, ...) that are released under a different license which does not allow redistribution under LGPL-3.0, to annotate that accordingly where we use the file (e.g. image byline). I don't know if this applies to any file for now, but I think we can fix that once we notice it.

All contributors have to agree to the changed license, or we cannot proceed. I've looked up who contributed to this content, including in the old git history of the previous website version. Those are:

* [ ] @boldt 
* [ ] @ChrizKu 
* [ ] @Halbelunge 
* [ ] @madiko 
* [ ] @M-a-r-i-a-n-n-e 
* [ ] @Natenom 
* [ ] @rotger711 
* [ ] @SubOptimal 
* [ ] @tobst 
* [x] @opatut 

Please notify me of any I forgot. Please press "review" on top and choose "accept changes" if you agree to publishing your content under the terms of the LGPL-3.0. If you disagree, please comment so. You are not obliged to agree.

2021-03-24 12:20 UTC, tobst approved these changes

2021-03-24 13:08 UTC, opatut commented
@ChrizKu please use the review function, as that is tracable. I will update the checklist.

2021-03-24 15:29 UTC, rotger711 commented
agree

2021-03-24 18:32 UTC, M-a-r-i-a-n-n-e commented
agree

2021-03-25 10:22 UTC, ChrizKu approved these changes

2021-03-25 10:53 UTC, madiko requested changes
ACHTUNG: Wir können die Website als Ganzes NICHT unter LGPL stellen. Das muss sogar ein Copy sein.

Hallo zusammen, 

so gern ich zustimmen würde. Das ist leider nicht möglich!

Warum?

Weil wir Design-Elemente und Medien (z. B. PDFs, Fotos, Film, Audio, Graphiken, Illustrationen usw.) haben werden, die unter Urheberrecht stehen, bei denen Persönlichkeitsrechte gewahrt werden müssen und/oder für die wir uns ggf. gesonderte Rechte, Lizenzen usw. einholen werden. Ich denke da nicht nur an unseren Blog sondern auch z. B. daran, dass wir zukünftig Forschungsergebnisse veröffentlichen werden, wo wir zum Teil explizit Freigaben benötigen, um es überhaupt zu dürfen.

Es spricht jedoch nichts dagegen, den Großteil aller Informationen möglichst als Creative Commonse oder auch unter LGPL zu veröffentlichen - eben dort, wo wir es können und wo es Sinn macht.

Wir werden hier pro Seite entscheiden müssen. Meine Idee: Wir fügen die Rechte zum einzelnen Element bzw. auf der jeweiligen Seite unten ein.

Wie das technisch geht, weiß ich schon. Ich werde es jedoch erst nach und nach umsetzen können. Ist kein Hexenwerk, nur viel Fleißarbeit.

Viele Grüße,
Franziska

Paul @opatut, würdest Du bitte die Abfrage wieder rausnehmen und stattdessen auf copy setzen? Danke!

2021-03-25 17:40 UTC, opatut commented
Also das ist aber nicht so geplant. Wir haben ganz viel content schon, und wer den hochgeladen hat muss jetzt natürlich Urheberrechte prüfen, insbesondere die Erlaubnis geben oder einholen dass diese Inhalte unter LGPL veröffentlicht/lizensiert/relizensiert werden dürfen. Das ist die Verantwortung der Contributors, die ich oben aufgelistet habe. Da alle Inhalte soweit mir bekann ist auch von diesen stammen, oder zumindest die Urheber:innen im nahen Umkreis bekannt sind und im Einzelfall "macht damit was ihr wollt" gesagt haben, sehe ich hier kein Problem.

>Großteil aller Informationen möglichst als Creative Commonse

Da haben wir uns nicht für entschieden, sondern wir haben die LGPL als Community-Entscheidung getroffen. Da brauchen wir jetzt nicht mit CC irgendwas anzufangen.

> Medien [...] haben werden

Das können wir dann immer noch im Einzelfall richtig regeln. Da wir eh nicht in jede Datei einen Copyright/License Header einfügen können (weil die meisten Dateiformate da keine Kommentare erlauben) müssen wir die Lizensierung über die README  abbilden. Da steht im Moment eine Formulierung drin, die klar macht, dass nicht zwingend alle Bestandteile unter der Lizenz stehen. Das können wir in dem Moment, wo wir wissen, welche Medien Ausnahmen sind zur Regel, an genau der gleichen Stelle konkretisieren.

Im Footer steht im Moment "licensed under LGPL-3.0" (oder sinngemäß), was wir dann um "unless otherwise noted" ergänzen können, wenn wir auch konkrete Teile (z.B. eingebettete Bilder) unter andere Lizenz integrieren. Das ist auch kein Problem.

Insofern sehe ich deinen Grund zur Sorge nicht.

> Abfrage wieder rausnehmen und stattdessen auf copy setzen

Was meinst du damit?

2021-03-25 17:42 UTC, Natenom approved these changes

2021-03-25 20:25 UTC, M-a-r-i-a-n-n-e approved these changes

2021-03-29 11:27 UTC, SubOptimal approved these changes
:+1:

2021-03-29 17:52 UTC, boldt approved these changes

2021-05-05 16:55 UTC, boldt commented
Was ist hier der Stand der Dinge?

2021-05-06 13:47 UTC, opatut commented
Wüsst ich auch gern. Es fehlt noch Zustimmung von @rotger711 und @Halbelunge, da wir die außerhalb von Github erreichen können sehe ich kein Problem die zu bekommen, scheinbar bekommen die einfach keine Notifications.

@madiko hatte Anmerkungen und sah die praktische Umsetzbarkeit nicht gegeben. Ich halte das aber schon so für umsetzbar, leider ist die Diskussion dort irgendwie verlaufen. Vielleicht könnten wir die wieder aufnehmen, meinetwegen auch direkt in Slack oder in einem Montagscall in BBB.

2021-05-06 14:27 UTC, tobst commented
@rotger711 hat auch zugestimmt

2021-05-12 19:28 UTC, tyll commented
fixes #35

2021-06-10 15:15 UTC, opatut commented
@madiko Leider blockiert dein Einspruch das weitere Vorgehen, bitte bringe dich wieder in die Diskussion ein und beantworte die offenen Fragen zu deinem Post. Ich möchte das Thema gern endlich abschließen. Danke :blush:

2021-06-15 08:18 UTC, madiko approved these changes

2021-06-15 08:21 UTC, madiko commented
Hallo zusammen, 

mit der Freigabe des Logos unter CC-BY-SA sind wir nun auch frei, die Website unter LGPL zu stellen. Bitte entschuldigt, dass ich die Freigabe daher bisher verweigerte. Mir war wichtig, dass wir hier keinen Fehler machen und dem Projekt langfristig schaden. 

Für die Zukunft wünsche ich mir, dass wir uns dann vor allem im Blog immer wieder an diese Lizenz erinnern und dranbleiben.

Viele Grüße, Franziska

2021-07-09 08:37 UTC, madiko commented
Dear @Halbelunge,
Dear @rotger711,

would you please let us know, what is keeping you from approving the LGPL licence, so that we can finally fix it? Thanks a bunch!

Hope, you are well. Stay healthy and curious ;-)

Best regards,
Franziska

2022-05-03 09:42 UTC, rotger711 approved these changes

2022-05-10 06:01 UTC, merged